version: '3.8'

name: jourloy
services:
    postgres:
        container_name: jourloy-postgres
        image: postgres:latest
        environment:
            POSTGRES_DB: "${POSTGRES_DB}"
            POSTGRES_USER: "${POSTGRES_USER}"
            POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
        ports:
            - "5432:5432"

    server:
        container_name: jourloy-server
        build:
            context: .
        volumes:
            - .:/app
        command: go run ./cmd/main.go
        env_file:
            - .env
        ports:
            - "10001:10001"
        depends_on:
            - postgres